//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AcademyKuumaLinjaXOXO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message
    {
        public int Message_Id { get; set; }
        public string Subject { get; set; }
        public string MessageText { get; set; }
        public System.DateTime SendTime { get; set; }
        public int From_Person_Id { get; set; }
        public bool PrivateMessage { get; set; }
        public Nullable<int> To_Person_Id { get; set; }
        public Nullable<System.DateTime> ExpireAt { get; set; }
        public string Category { get; set; }
    
        public virtual Person Person { get; set; }
    }
}
